export default function Head() {
	return (
		<>
			<title>CONAN RPG</title>
			<link rel="icon" href="/favicon.ico" />
			<meta
				content="width=device-width, initial-scale=1"
				name="viewport"
			/>
			<meta name="description" content="Generated by create next app" />
		</>
	);
}
